# Generated by Django 2.2.5 on 2019-09-26 20:53

from django.db import migrations, models
import django_callablefield.hook


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ab_key', django_callablefield.hook.HookField(max_length=32)),
            ],
        ),
    ]
