# Generated by Django 2.2.5 on 2019-09-25 15:11

from django.db import migrations, models
import django_callablefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ab', django_callablefield.fields.ABField()),
            ],
        ),
    ]
